### ISSUE TITLE
Look into Babel-eslint

### ISSUE THREAD

**Issue by Globegitter** [artificialio/sane#108]
It seems [eslint](http://eslint.org/) might be a viable alternative to JSHint, especially because we could get future JS support via https://github.com/babel/babel-eslint.

**Comment by kriswill** [comment]
I've looked into eslint before and the only negative that I had found about it, is that it's slower than JSHint.  other than that I think it does an adequate linting job.

**Comment by mgenev** [comment]
was this the one which @IanVS added, is this ready to close?

**Comment by Globegitter** [comment]
Yep that can be closed.
