### ISSUE TITLE
Investigate sane up with no global ember-cli

### ISSUE THREAD

**Issue by Globegitter** [artificialio/sane#111]
When `sane up` is run we just spawn with the string `ember` (https://github.com/artificialio/sane/blob/master/lib/commands/up.js#L108) which assumes that a global version is installed, which then resolves to the local version. So we should either have our own resolver, or use the local version straight in all cases.

**Comment by jhliberty** [comment]
I think serving a local version is a good idea as a default so we can couple the versions of sails and ember for stability but allow it to be overridden if desired.

**Comment by Globegitter** [comment]
We now have https://github.com/artificialio/sane/pull/112 which just needs to be fixed for our tests.

**Comment by jhliberty** [comment]
Awesome!

**Comment by Globegitter** [comment]
@jhliberty If you feel up for contributing that is a good chance to get started.

**Comment by IanVS** [comment]
I'm going to take a crack at solving this since multiple people have run into problems.

**Comment by mpedrera** [comment]
Arrived here by following [this issue](https://github.com/mgenev/how-to-sane/issues/16), since I got the same error after cloning and following instructions.

Didn't have `ember-cli` installed globally, so I installed it and issue went away. Is this supposed to be fixed?

**Comment by IanVS** [comment]
It is supposed to be fixed, yes.  Did you clone from master and run `npm link`, not `npm install -g sane-cli`?  As far as I know, there is no npm version with the fix in place.
