### ISSUE TITLE
Add Nodemon to the sane up to restart sailsjs after code changes

### ISSUE THREAD

**Issue by kiwiupover** [artificialio/sane#124]
When I make changes to the server I would like sails to restart.

**Comment by mgenev** [comment]
not sure on what the status is, but I believe @Globegitter is/was/intends to use the sails reload hook, we'll have to hear from him

**Comment by kiwiupover** [comment]
@mgenev sounds good.

**Comment by mgenev** [comment]
he's traveling for a bit though...

**Comment by Globegitter** [comment]
Well, right now you have https://github.com/sgress454/sails-hook-autoreload which automatically restarts the server and with docker you can also use the pm2 image.

**Comment by kiwiupover** [comment]
I'm not running with docker and I was editing blueprints then I had to restart the sane. 

Maybe we need to add the blueprints to autoreload hook?

FYI you guys are right on top of things here.

**Comment by kiwiupover** [comment]
Blueprints are apart of the config autoreload. 

How ever the server is not reloading for me. 

I believe i'm using @alpha4

```js
var path = require('path');

module.exports.autoreload = {
  active: process.env.NODE_ENV === undefined || process.env.NODE_ENV ==='development',
  //use polling to watch file changes
  //slower but needed for the docker image
  usePolling: false,
  // Set dirs to watch
  dirs: [
    path.resolve('api','blueprints'),
    path.resolve('api','controllers'),
    path.resolve('api','models'),
    path.resolve('api','policies'),
    path.resolve('api','responses'),
    path.resolve('api','services'),
    path.resolve('config')
  ]
};
```

**Comment by Globegitter** [comment]
Ah yeah, there is now a slight disparity between alpha and master. So master is installing sails-hook-autorelad, where-as the alpha4 is not. The plan is for beta for the to be on par again. 

But yeah, if you go to your server folder `npm i sails-hook-autoreload` and add `https://github.com/artificialio/sane/blob/master/templates/server/config/autoreload.js.hbs` to your config you should be good to go.

**Comment by kiwiupover** [comment]
perfect! thanks @Globegitter
