### ISSUE TITLE
In Windows, error when using sane's local ember-cli

### ISSUE THREAD

**Issue by IanVS** [artificialio/sane#128]
When running `sane new <projectname>`, if the globally installed version of `ember-cli` is different from that in `sane`, a choice is given to the user of which one to use.  Unfortunately, on Windows it is impossible to use the locally installed version because there is no `ember.cmd` file that Windows can run.  NPM adds that file upon global installation.

**Comment by brandensilva** [comment]
+1 I'm having this issue on Windows as well. This cause the "tooling is installing packages via npm" to continue indefinitely after the "sails.cmd cannot be found. Error code 1." and it manages to generate a folder structure so long that you can't physically delete it on windows (didn't think that was possible) without doing some rm -rf magic with some linux based tools. 

Luckily I use a lot of linux based stuff on my machine so it wasn't a problem, but I sure hope this gets fixed soon.

**Comment by brandensilva** [comment]
I forgot to mention this happens whether you use the local version or sane version so it may be another issue.

**Comment by IanVS** [comment]
Do you have sails.js installed globally? I think you must, just checking to be sure.  It seems to be something to do with Sails or ember-generate which is failing. I'll try to reproduce the error tomorrow.  Are you running the official SANE 0.0.24 release? (as opposed to cloning and linking)

**Comment by IanVS** [comment]
@brandensilva, I am not able to reproduce the problem you describe here.  Can you give some more information about what versions of SANE, Sails, and Node you're using?

**Comment by brandensilva** [comment]
I'll do a bit more testing on my end and get back to you. I tested sane
0.24 on another machine and had it working so its likely something isolated
on my main machine.

**Comment by IanVS** [comment]
OK I'm going to close this for now then.  If you do some more research and find that this is in fact a SANE bug, please reopen it.

**Comment by IanVS** [comment]
Actually, the original problem is still valid.  It should be fixed when we implement a more robust way of resolving the ember binary.
