### ISSUE TITLE
auto re-start sails when code change

### ISSUE THREAD

**Issue by feitian124** [artificialio/sane#131]
ember-cli is powerful and if code get changed, the 'compile' layer automatically re-compile so you can see  changes immediately. 

however sails do not have this ability so if code changed we have to re-start sane, which is slow and do too much, as we only need re-start sails.

how about add a option to sane up command, for example
```sh
sane up --watch
```
to let we run `sails lift` under something like [nodemon](https://github.com/remy/nodemon) so if server side code changes, we get `sails lift` re-lift again?

**Comment by IanVS** [comment]
This can, in fact, already be done!  Install `sails-hook-autoreload` into your `server/` directory.  If you try this and have problems, feel free to re-open the issue, but for now I'm going to close.

**Comment by feitian124** [comment]
cool, thanks.
