### ISSUE TITLE
sane's sails does not save models sent by ember in new app

### ISSUE THREAD

**Issue by BransonGitomeh** [artificialio/sane#140]
i did **sane g resource pet name:string age:string** 

made a **textbox and an action to save the name and age of the pet**

save on ember data shows up on inspector but on refresh the values returned are **undefined**

fired up postman and tested the api from sails and i got this

![image](https://cloud.githubusercontent.com/assets/11181583/7133990/950d6e4c-e266-11e4-9c83-15c8ccfb531c.png)

as you can see it doesn't save the data sent to it, but receives the **post request**

a new sailsjs app on my laptop does not have this issue so my sails is ok and if thte postman code does not work then my ember save code was ok too

ive gotten this for almost all the time....is this a bug?...

*please help............*

**Comment by Globegitter** [comment]
First of all try the 'Raw' tab and send

```js
{
  "pet": {
    "name": "puppy",
    "age": "30"
  }
}
```

and see if that works. But that means that something with https://github.com/mphasize/sails-generate-ember-blueprints and ember-data isn't hooked up properly.

Can you check which version you have of both? The one version you can find in `server/package.json` and the other when you start your ember app and open the Chrome dev tools, it will print out the ember-data version you are using.

**Comment by Globegitter** [comment]
Just tested in my app and at least sending a 'raw' JSON from postman works as intended.

**Comment by Globegitter** [comment]
![screen shot 2015-04-14 at 11 58 15](https://cloud.githubusercontent.com/assets/2580254/7135329/8ed6418e-e29d-11e4-821a-955223c20f56.png)

Works for me on a fresh sane project. Could you maybe share a repo so we can reproduce the bug with the ember frontend?

**Comment by tarlepp** [comment]
I have this same problem with fresh install of sane. Post works fine with Raw input, but not with form-data nor x-www-form-urlencoded

On my ```server/package.json``` I have ```"sails-generate-ember-blueprints": "0.0.6"```

**Comment by jamemackson** [comment]
The format ember generates is how the server is setup and expects that your attributes be passed in like @Globegitter described above.  This is why using the raw format works and the others do not.  This is by design.

**Comment by mgenev** [comment]
@tarlepp it would be worth it to see, what kind of request ember sends
here's an example:
```
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,es;q=0.6,bg;q=0.4
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im1nZW5ldkBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJtYXJ0aW4iLCJsYXN0TmFtZSI6ImdlbmV2IiwidXNlclR5cGUiOjAsImNyZWF0ZWRBdCI6IjIwMTUtMDQtMTJUMjM6MjM6NTIuMjMyWiIsInVwZGF0ZWRBdCI6IjIwMTUtMDQtMTJUMjM6MjM6NTIuMjMyWiIsImlkIjoiNTUyYWZlODg0NjE1MWQ5ODA4ZTI5MTBlIiwiaWF0IjoxNDI5MDIzMTM3LCJleHAiOjE0MjkwMzAzMzd9.XhkRMquQmHJtir4wpyEkWmhaa3Lm8hVjWfgxg3AQmqI
Cache-Control:no-cache
Connection:keep-alive
Content-Length:110
Content-Type:application/json; charset=UTF-8
Cookie:sails.sid=s%3A8KQqMS5WRZlfRxf5MPJxkLzsptJ5jBoA.S%2FJHFi9X2cOkTpNeBPD2PCbRS32ExmbXNR%2FL1rDrQg0
Host:howtosane.ninja
Origin:http://howtosane.ninja
Pragma:no-cache
Referer:http://howtosane.ninja/s/posts/create
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.82 Safari/537.36
X-Requested-With:XMLHttpRequest
```

You can play with a live Sane app here - http://howtosane.ninja

**Comment by BransonGitomeh** [comment]
@globegitter im not in a position to try this stuff right now..but tommorow...in like 9hrs :-)

**Comment by BransonGitomeh** [comment]
@globegitter im not in a position to try this stuff right now..but tommorow...in like 9hrs :-)

**Comment by Globegitter** [comment]
Seems like it is working.
