### ISSUE TITLE
Multiple errors on windows 8.1

### ISSUE THREAD

**Issue by jimmyjamieson** [artificialio/sane#147]
I'm tearing my hair out here. Tying to get sane installed on windows 8.1 (Why didn't I buy a mac?).

I've tried installing, uninstalling, trying different versions of node, deleting my global node modules.

Installing i get loads of red errors e.g:

`
npm install sane -g
> ws@0.5.0 install C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli\node_m
odules\ember-cli\node_modules\testem\node_modules\socket.io\node_modules\engine.
io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/
C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli\node_modules\ember-cli\no
de_modules\testem\node_modules\socket.io\node_modules\engine.io\node_modules\ws>
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\n
pm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  els
e (rebuild)
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  bufferutil.cc
..\src\bufferutil.cc(32): warning C4996: 'NanSymbol': was declared deprecated [
C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli\node_modules\ember-cli\n
ode_modules\testem\node_modules\socket.io\node_modules\engine.io\node_modules\w
s\build\bufferutil.vcxproj]
          C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli\node_modules\e
  mber-cli\node_modules\testem\node_modules\socket.io\node_modules\engine.io\no
  de_modules\ws\node_modules\nan\nan.h(616) : see declaration of 'NanSymbol'
     Creating library C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli\no
  de_modules\ember-cli\node_modules\testem\node_modules\socket.io\node_modules\
  engine.io\node_modules\ws\build\Release\bufferutil.lib and object C:\Users\Ia
  n\AppData\Roaming\npm\node_modules\sane-cli\node_modules\ember-cli\node_modul
  es\testem\node_modules\socket.io\node_modules\engine.io\node_modules\ws\build
  \Release\bufferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli\
  node_modules\ember-cli\node_modules\testem\node_modules\socket.io\node_module
  s\engine.io\node_modules\ws\build\Release\\bufferutil.node
  validation.cc
..\src\validation.cc(112): warning C4996: 'NanSymbol': was declared deprecated
[C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli\node_modules\ember-cli\
node_modules\testem\node_modules\socket.io\node_modules\engine.io\node_modules\
ws\build\validation.vcxproj]
          C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli\node_modules\e
  mber-cli\node_modules\testem\node_modules\socket.io\node_modules\engine.io\no
  de_modules\ws\node_modules\nan\nan.h(616) : see declaration of 'NanSymbol'
     Creating library C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli\no
  de_modules\ember-cli\node_modules\testem\node_modules\socket.io\node_modules\
  engine.io\node_modules\ws\build\Release\validation.lib and object C:\Users\Ia
  n\AppData\Roaming\npm\node_modules\sane-cli\node_modules\ember-cli\node_modul
  es\testem\node_modules\socket.io\node_modules\engine.io\node_modules\ws\build
  \Release\validation.exp
  Generating code
  Finished generating code
  validation.vcxproj -> C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli\
  node_modules\ember-cli\node_modules\testem\node_modules\socket.io\node_module
  s\engine.io\node_modules\ws\build\Release\\validation.node

> ws@0.4.31 install C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli\node_
modules\ember-cli\node_modules\testem\node_modules\socket.io\node_modules\socket
.io-client\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli\node_modules\ember-cli\no
de_modules\testem\node_modules\socket.io\node_modules\socket.io-client\node_modu
les\engine.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C
:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\nod
e-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targe
ts(308,5): error MSB3491: Could not write lines to file "Release\obj\bufferutil
\bufferutil.tlog\bufferutil.lastbuildstate". The specified path, file name, or
both are too long. The fully qualified file name must be less than 260 characte
rs, and the directory name must be less than 248 characters. [C:\Users\Ian\AppD
ata\Roaming\npm\node_modules\sane-cli\node_modules\ember-cli\node_modules\teste
m\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-c
lient\node_modules\ws\build\bufferutil.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targe
ts(308,5): error MSB3491: Could not write lines to file "Release\obj\validation
\validation.tlog\validation.lastbuildstate". The specified path, file name, or
both are too long. The fully qualified file name must be less than 260 characte
rs, and the directory name must be less than 248 characters. [C:\Users\Ian\AppD
ata\Roaming\npm\node_modules\sane-cli\node_modules\ember-cli\node_modules\teste
m\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-c
lient\node_modules\ws\build\validation.vcxproj]
C:\Users\Ian\AppData\Roaming\npm\sane -> C:\Users\Ian\AppData\Roaming\npm\node_m
odules\sane-cli\bin\sane
sane-cli@0.0.24 C:\Users\Ian\AppData\Roaming\npm\node_modules\sane-cli
├── pleasant-progress@1.0.2
├── commander@2.6.0
├── readline-sync@0.7.9
├── walk-sync@0.1.3
├── node-uuid@1.4.3
├── exit@0.1.2
├── shelljs@0.3.0
├── child-process-promise@1.0.2 (q@1.2.0)
├── resolve@1.1.6
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1
.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── fs-extra@0.16.5 (jsonfile@2.0.0, graceful-fs@3.0.6, rimraf@2.3.2)
├── captains-log@0.11.11 (merge-defaults@0.1.4, colors@0.6.2, rc@0.3.5, lodash@2
.4.1)
├── yam@0.0.18 (findup@0.1.5, lodash.merge@3.2.0)
├── handlebars@3.0.2 (optimist@0.6.1, source-map@0.1.43, uglify-js@2.3.6)
├── traceur@0.0.85 (semver@2.3.2, glob@4.3.5, source-map-support@0.2.10, rsvp@3.
0.18)
├── leek@0.0.17 (rewire@2.3.1, debug@2.1.3, lodash@2.4.1, rsvp@3.0.18, request@2
.55.0)
├── configstore@0.3.2 (object-assign@2.0.0, xdg-basedir@1.0.1, user-home@1.1.1,
osenv@0.1.0, graceful-fs@3.0.6, uuid@2.0.1, mkdirp@0.5.0, js-yaml@3.2.7)
└── ember-cli@0.2.3 (broccoli-unwatched-tree@0.1.1, is-git-url@0.2.0, abbrev@1.0
.5, ember-cli-copy-dereference@1.0.0, broccoli-writer@0.1.1, promise-map-series@
0.2.1, js-string-escape@1.0.0, broccoli-merge-trees@0.2.1, temp@0.8.1, strip-ans
i@2.0.1, semver@4.3.3, debug@2.1.3, broccoli-sane-watcher@1.0.2, broccoli-filter
@0.1.12, http-proxy@1.11.0, rsvp@3.0.18, broccoli-funnel@0.2.2, symlink-or-copy@
1.0.1, rimraf@2.3.2, broccoli-kitchen-sink-helpers@0.2.6, sane@1.0.3, markdown-i
t@4.0.3, ember-router-generator@0.3.3, broccoli-es3-safe-recast@2.0.0, broccoli-
es6modules@0.5.1, broccoli-caching-writer@0.5.5, broccoli-sourcemap-concat@0.4.4
, core-object@0.0.2, markdown-it-terminal@0.0.2, testem@0.8.0) `

## and 'sane up' shows: ##

`
 server   |
server   | info: Starting app...
server   |
client   | version: 0.2.3
client   | Cannot find module 'ember-cli/lib/broccoli/ember-app'
client   | Error: Cannot find module 'ember-cli/lib/broccoli/ember-app'
client   |     at Function.Module._resolveFilename (module.js:336:15)
client   |     at Function.Module._load (module.js:278:25)
client   |     at Module.require (module.js:365:17)
client   |     at require (module.js:384:17)
client   |     at Object.<anonymous> (C:\Users\Ian\Dropbox\Web\Clients\_projects
\maltadz\client\Brocfile.js:3:16)
client   |     at Module._compile (module.js:460:26)
client   |     at Object.Module._extensions..js (module.js:478:10)
client   |     at Module.load (module.js:355:32)
client   |     at Function.Module._load (module.js:310:12)
client   |     at Module.require (module.js:365:17)
server   | module.js:338
server   |     throw err;
server   |     ^
server   | Error: Cannot find module 'sails-generate-ember-blueprints/templates/
basic/api/services/Ember.js'
server   |     at Function.Module._resolveFilename (module.js:336:15)
server   |     at Function.Module._load (module.js:278:25)
server   |     at Module.require (module.js:365:17)
server   |     at require (module.js:384:17)
server   |     at Object.<anonymous> (C:\Users\Ian\Dropbox\Web\Clients\_projects
\maltadz\server\api\services\Ember.js:1:80)
server   |     at Module._compile (module.js:460:26)
server   |     at Object.Module._extensions..js (module.js:478:10)
server   |     at Module.load (module.js:355:32)
server   |     at Function.Module._load (module.js:310:12)
server   |     at Module.require (module.js:365:17)
server   |     at require (module.js:384:17)
server   |     at C:\Users\Ian\AppData\Roaming\npm\node_modules\sails\node_modul
es\include-all\index.js:129:29
server   |     at Array.forEach (native)
server   |     at requireAll (C:\Users\Ian\AppData\Roaming\npm\node_modules\sail
s\node_modules\include-all\index.js:44:9)
server   |     at buildDictionary (C:\Users\Ian\AppData\Roaming\npm\node_modules
\sails\node_modules\sails-build-dictionary\index.js:68:14)
server   |     at Function.module.exports.optional (C:\Users\Ian\AppData\Roaming
\npm\node_modules\sails\node_modules\sails-build-dictionary\index.js:160:9)
`

I feel like giving up and continuing with ember-cli/firebase, but think this is a better option.

**Comment by jimmyjamieson** [comment]
Fixed it by installing https://msdn.microsoft.com/en-us/windows/desktop/bg162891.aspx

I already have visual studio express for windows desktop.

**Comment by Globegitter** [comment]
@jimmyjamieson Glad you found the solution!
