### ISSUE TITLE
docker-sails image should do a clean npm install of required packages

### ISSUE THREAD

**Issue by DiknT** [artificialio/sane#149]
The currently used [docker image docker-sails](https://registry.hub.docker.com/u/artificial/docker-sails/) does not npm install required packages but only mounts the /server folder containing the node_modules folder. Some dependencies like bcrypt need to be compiled on the target container os to work. So developing on OS X for example and trying to start docker with this image does not work.

The official node image for example does a npm install by default which could solve this problem I guess.

**Comment by Globegitter** [comment]
@DiknT good idea, for now you can manually do that by running `docker-compose run server npm install`

**Comment by maxwerr** [comment]
All about this, thanks @Globegitter. Is there any realted plan to make this more obvious/integrated?
