### ISSUE TITLE
Main page Flatdoc error

### ISSUE THREAD

**Issue by jasalguero** [artificialio/sane#153]
Whenever I try to load the main page, everything is empty and on the javascript console I can the error:

    Uncaught ReferenceError: Flatdoc is not defined

**Comment by Globegitter** [comment]
@jasalguero can you open up the network tab of your Chrome/FF Dev Tools and and see what it says about loading flatdoc.js? Seems for some reason it does not load for you.

**Comment by jasalguero** [comment]
Only resource is not loaded correctly is a css, I see the flatdoc.js being loaded correcty.

![screen shot 2015-05-02 at 23 18 12](https://cloud.githubusercontent.com/assets/504847/7442818/916b9f24-f121-11e4-933d-625d8c5144ee.png)

**Comment by kernicPanel** [comment]
My two cents here : flatdoc seems loaded, but server response is empty.

**Comment by kernicPanel** [comment]
rawgit issue opened here : rgrove/rawgit/issues/64

**Comment by jasalguero** [comment]
That seems to have solved the issue :+1:  Thanks!
