### ISSUE TITLE
hangs on install

### ISSUE THREAD

**Issue by shaunc** [artificialio/sane#164]
on darwin, node 0.12.4, with docker otherwise working, install hangs when I follow quickstart instructions:

sane new project --docker
Detected different versions for sane's locally installed ember-cli (0.2.7) and your global one (0.1.15). Want to use sane's one? (y/n):  (y) y
Sane version: 0.0.24

Setting up Sails project and downloading latest Docker Containers.
sails version: info: Created a new Sails app `server`!
Installed Sails packages for tooling via npm.

Setting up Ember project locally.
ember-cli version: 0.2.7
installing
  create .bowerrc
  create .editorconfig
  create .ember-cli
  create .jshintrc
  create .travis.yml
  create .watchmanconfig
  create Brocfile.js
  create README.md
  create app/app.js
  create app/components/.gitkeep
  create app/controllers/.gitkeep
  create app/helpers/.gitkeep
  create app/index.html
  create app/models/.gitkeep
  create app/router.js
  create app/routes/.gitkeep
  create app/styles/app.css
  create app/templates/application.hbs
  create app/templates/components/.gitkeep
  create bower.json
  create config/environment.js
  create .gitignore
  create package.json
  create public/crossdomain.xml
  create public/robots.txt
  create testem.json
  create tests/.jshintrc
  create tests/helpers/resolver.js
  create tests/helpers/start-app.js
  create tests/index.html
  create tests/test-helper.js
  create tests/unit/.gitkeep
  create vendor/.gitkeep
Installing packages for tooling via npm  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
Installing packages for tooling via npm.  SOLINK_MODULE(target) Release/bufferutil.node
Installing packages for tooling via npm..  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
Installing packages for tooling via npm...  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
Installing packages for tooling via npm.  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
Installed packages for tooling via npm.
Installed browser packages via Bower.
Running tooling scrips for Sane.ENOENT, no such file or directory 'server/config/autoreload.js'
Running tooling scrips for Sane...

---
It has been there for ~1 hour and previous try got to same point

**Comment by shaunc** [comment]
... after interrupting, switching to project directory and trying to bring up system I get:

Shauns-MacBook-Pro:project shauncutts$ sane up
docker-compose
Creating project_server_1...
Attaching to project_server_1
server_1 | 
server_1 | info: Starting app...
server_1 | 
server_1 | error: Error: Cannot find module 'lodash/Lang/isObject'

---

Any other things I can try to diagnose?

**Comment by IanVS** [comment]
The first issue you posted should be taken care of in the upcoming 0.1.0 release, but it only has to do with not exiting correctly, everything likely installed just fine. 

The other issue you posted is due to a bug in sails-hook-dev.  The solution for now is to change your package.json in the server directory to use `balderdashy/sails-hook-dev` as the version of sails-hook-dev.  Then `rm - rf node_modules/sails-hook-dev && npm install`

Try that and see if it takes care of your issue.

**Comment by shaunc** [comment]
Ok ... I installed sane & sails globally as quickstart suggests. hmm... seems not to be a package.json in the server directory -- just in the root of the project, and that only has "sane-cli" listed in dependencies. Should I put sails-hook-dev here? .. Should I first install a local copy of sails in the "project" root?

**Comment by jamemackson** [comment]
There should definitely be a package.json in the root of the server directory.  Maybe the project creation failed?  Try another new project after updating sane etc.  But there is no need for that package in the root of the project.

**Comment by shaunc** [comment]
Hmm... client looks like full ember client, but server just has 

    | |____server
    | | |____api
    | | | |____controllers
    | | | |____responses
    | | |____assets

So ... perhaps install failed after all? ... any steps to diagnose? Is there a "verbose" mode?

**Comment by IanVS** [comment]
Honestly, I would recommend trying out the beta SANE version. `npm install -g sane-cli@beta`. And then try creating a new project.

**Comment by shaunc** [comment]
... hmm... still going but got:

---
Installing Sails packages for tooling via npm...`docker-compose run server npm i sails-generate-ember-blueprints lodash pluralize sails-hook-autoreload@~0.11.4 sails-hook-dev@balderdashy/sails-hook-dev sails-disk --save` failed with code 1
undefined

---
Didn't get that before. There was still running:

----

$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                    NAMES
8bc0aed1c77e        postgres:9          "/docker-entrypoint.   2 hours ago         Up 2 hours          0.0.0.0:5432->5432/tcp   testsane_db_1  

----

as once before I test w/ postgres. This time I didn't specify db though, and presumably docker compose would use another name anyway? Well will kill and try again but any helpful suggestions appreciated. :)

**Comment by shaunc** [comment]
btw ...
Shauns-MacBook-Pro:project shauncutts$ docker-compose --version
docker-compose 1.1.0
Shauns-MacBook-Pro:project shauncutts$ docker --version
Docker version 1.5.0, build a8a31ef

Should I try a newer version of docker-compose?

**Comment by shaunc** [comment]
Opinions on docker-compose -- should I try 1.3.0rc1? I don't know if you depend on specific version -- seems there are some changes in 1.3 --

> Compose now uses Docker labels, rather than container names, to keep track of containers. This is both cleaner and more performant.

**Comment by shaunc** [comment]
Hmm... inside the docker-compose.yml I see

> server:
  #Docker-sails supports several different tags:
  #0.10.32/33/34 (node 0.10.32), stable (latest node 0.10.x), latest (latest node 0.11.x)
  #0.10.32/33/34-pm2 (node 0.10.32), stable-pm2 (latest node 0.10.x), latest-pm2 (latest node 0.11.x)

Locally I am using node 0.12.4 -- I don't know why this would interfere with docker image though... but perhaps something else is going on. Have you tested node 0.12.X?

**Comment by shaunc** [comment]
NB the "stable" branch of node is now 0.12 -- perhaps you guys could spin one up on docker? I'm see you are mounting server and using the image to run npm ... but I'm not sure that will work with my local node 0.12? Also from which version of npm did it start loading from github with that syntax? I seem to recall that was a pretty recent update.....

**Comment by shaunc** [comment]
**OK**:

1) I don't think your "beta" version is quite ready yet.
2) initial problem was that my home directory is symlinked to another drive due to space problems -- and boot2docker on mac needs to mount under /Users (sorry about that -- had forgotten!) Beta still breaks as above but current release did install once I moved to a suitable directory for docker.
3) Still wish you would try building under 0.12
