### ISSUE TITLE
Cannot create new project

### ISSUE THREAD

**Issue by oscartobio** [artificialio/sane#166]
On OSX
npm install -g ember-cli@0.2.7
npm install -g sails@0.11.0
npm install -g sane-cli@0.1.0-beta.1
sane new sane-auth-example
Detected different versions for sane's locally installed ember-cli (0.2.7) and your global one (undefined).
Want to use sane's local Ember? (y/n):  (y) y
Sane version: 0.1.0-beta.1

Setting up Sails project locally.

Quits immediately creating an empty "Server" folder. What am I missing ?

**Comment by IanVS** [comment]
This should be solved in `sane-cli@0.1.0-beta.2`.  Can you please try it and let us know if it works?

**Comment by oscartobio** [comment]
Solved on beta.2   Thanks Ian.
