### ISSUE TITLE
Can't install bcrypt via `docker-compose run server npm install` due to missing $PYTHON

### ISSUE THREAD

**Issue by maxwerr** [artificialio/sane#182]
I'm having the original issue from https://github.com/artificialio/sane/issues/149 and I can't seem to get it to work even with `docker-compose run server npm install`. Appears that python isn't installed (and it's location not set to `$PYTHON`). Is there a (simple) way to install python onto the docker-sails image?

**Comment by Globegitter** [comment]
@maxwerr If I remember correctly the default docker image comes without python. If you switch to `iojs-full-stable` you should be able to install it. You can also use https://github.com/dcodeIO/bcrypt.js which does not need python installed.

**Comment by kriswill** [comment]
@Globegitter not sure if you're aware, but lots of native modules break with latest io.js v3.0.0, and bcrypt is one of them.  Mostly due to `nan` interface deprecations.  I ran into this while attempting to upgrade the Dockerfile.

**Comment by maxwerr** [comment]
@Globegitter that works great and `docker-compose run server npm install` has no trouble--thank you!
@kriswill I didn't realize that, but it's v. handy to know... :sweat_smile: I'm currently just trying to get the https://github.com/mgenev/how-to-sane/ example(s) working inside boot2docker.
