### ISSUE TITLE
Give up on sails-hook-dev

### ISSUE THREAD

**Issue by IanVS** [artificialio/sane#188]
It's been months waiting for a release to include the fix for https://github.com/balderdashy/sails-hook-dev/issues/6.  It's time to give up and move on.

**Comment by BransonGitomeh** [comment]
yup :100: %

**Comment by kriswill** [comment]
It's a handy module... I've noticed that there are a lot of these kinds of latent npm publish problems out of the Sails team.

**Comment by IanVS** [comment]
Yeah it's a shame.  If anyone wants to use it of course they can still `npm install` from github master, but it was the source of a lot of issues within SANE.  If they ever publish a new version, we can put it back in.
