### ISSUE TITLE
Call the new org SaneJS

### ISSUE THREAD

**Issue by nahtnam** [artificialio/sane#192]
Hey!

I would like to suggest calling the new org SaneJS so when I search things up, I don't get information about the mind... :P

**Comment by IanVS** [comment]
Sorry, but the naming SANE follows the tradition of MEAN stack, and it's not really a library in-and-of-itself so much as a CLI tool, so I don't think adding ".JS" to the end is appropriate.  Thanks for the suggestion though.  For searching, I'd suggest adding words like "Ember", "Sails", or "JavaScript" to your query.
