### ISSUE TITLE
Require specification of --javascript or --coffeescript, default to most popular

### ISSUE THREAD

**Issue by devinrhode2** [artificialio/sane#21]
The idea is to require a --javascript or --coffeescript flag when creating a new project, gather analytics like bower and ember-cli, and set the default to what is most popular among Sane users.

**Comment by Globegitter** [comment]
Basic analytics have been implemented. Probably a few more things could be done though.

**Comment by mgenev** [comment]
i'm personally strongly against a coffeescript default

**Comment by devinrhode2** [comment]
And I'm personally **for** a coffeescript default


-Devin <http://zerply.com/DevinRhode2>
<http://zerply.com/devinrhode2>

**Comment by mgenev** [comment]
Sorry, it won't happen. I consider it an anti-pattern and completely illogical for a default of an full javascript stack.

**Comment by kriswill** [comment]
Coffescript is a beautiful alternative syntax that borrows heavily from the pythonic tradition.  Whereas, JavaScript borrows it's syntax from C and Java.  I personally love it, and wish that Coffeescript was the syntax I could use for my every day work.  It's easier to read and easier to type, and has a lot of convenience shortcuts for doing repetitive things in Javascript.

However, a majority of javascript coders seem to have a strong preference for plain-ole C syntax, and are resistant to learning Coffeescript syntax.  So, using the syntax that everyone knows by default is why it is the default.

**Comment by Globegitter** [comment]
I think there is a lot to like about the Coffeescript syntax and it might come as a flag if more people request it but will not be default. This is now tracked here: https://github.com/artificialio/sane/issues/56
