### ISSUE TITLE
General problem

### ISSUE THREAD

**Issue by mbwe** [artificialio/sane#23]
Hi all,

First of all i am a new webdeveloper, and have not much experience with sails.js or ember.js. 

I installed sane, as suggested on the sane webpage. Everything works fine, however when i run "sane up" i get the following output when i try to connect.

server   | 
server   | [32minfo: [39m[90mStarting app...[39m
server   | 
client   | version: 0.1.4
server   | [32minfo: [39m
server   | [32minfo: [39m
server   | [32minfo: [39m   Sails              <|
server   | [32minfo: [39m   v0.10.5             |\
server   | [32minfo: [39m                      /|.\
server   | [32minfo: [39m                     / || \
server   | [32minfo: [39m                   ,'  |'  \
server   | [32minfo: [39m                .-'.-==|/_--'
server   | [32minfo: [39m                `--'-------' 
server   | [32minfo: [39m   __---___--___---___--___---___--___
server   | [32minfo: [39m ____---___--___---___--___---___--___-__
server   | [32minfo: [39m
server   | [32minfo: [39mServer lifted in `/home/agent/Development/bdproject/server`
server   | [32minfo: [39mTo see your app, visit [4mhttp://localhost:1337[24m
server   | [32minfo: [39mTo shut down Sails, press <CTRL> + C at any time.
server   | [37m[39m
server   | [34mdebug: [39m[90m--------------------------------------------------------[39m
server   | [34mdebug: [39m[90m:: Mon Dec 08 2014 21:18:35 GMT+0100 (CET)[39m
server   | [37m[39m
server   | [34mdebug: [39mEnvironment : development
server   | [34mdebug: [39mPort        : 1337
server   | [34mdebug: [39m[90m--------------------------------------------------------[39m
client   | Could not find watchman, falling back to NodeWatcher for file system events
client   | Proxying to 127.0.0.1:1337
client   | Livereload server on port 35729
client   | Serving on http://0.0.0.0:4200/
client   | 
client   | Build successful - 869ms.
client   | 
client   | Slowest Trees                  | Total          
client   | -------------------------------+----------------
client   | EsnextFilter                   | 214ms          
client   | Concat                         | 132ms          
client   | EsnextFilter                   | 114ms          
client   | ES6Concatenator                | 59ms           
client   | JSHint - App                   | 57ms           
client   | ES3SafeFilter                  | 51ms           
client   | 
client   | 
client   | Error: connect EINVAL
client   |     at errnoException (net.js:904:11)
client   |     at connect (net.js:766:19)
client   |     at net.js:845:9
client   |     at asyncCallback (dns.js:68:16)
client   |     at Object.onanswer [as oncomplete] (dns.js:121:9)
 

When i reload the page, the page is not loaded anymore. Could you please give me some pointers how to resolve this. And if its a bug i am glad i could help :)

Greetings,

Mbwe

**Comment by Globegitter** [comment]
@mbwe As talked on gitter you had some success?

**Comment by mbwe** [comment]
@Globegitter yes i had success, i have not encountered the problem again with sanestack version 0.0.17.
