### ISSUE TITLE
Look into fig issues

### ISSUE THREAD

**Issue by Globegitter** [artificialio/sane#29]
https://github.com/docker/fig/issues/328
https://github.com/docker/fig/issues/118
https://github.com/docker/fig/issues/637

```
Cannot start container 58c36325805586d122dbda8fa7c66e3aa5b979749695ada0fd8cfc2e0fdc2826: Cannot link to a non running container: /myprojectnew_db_1 AS /myprojectnew_server_1/myprojectnew_db_1
```
turns into

```js
server_1 | error: A hook (`orm`) failed to load!
server_1 | error: Error: failed to connect to [db:27017]
```

**Comment by Globegitter** [comment]
Haven't had this issue anymore in a long time.

**Comment by anasyb** [comment]
am having this issue.. can't load the server any more after a reboot.
running the db on its own using `docker-compose run db` shows everything is normal and its listening on port 270... Doing `sane up` or `docker-compose run server sails console` says throws that `orm` error. For a moment I thought sails is running too fast, the db isn't yet listening on the port... but not sure. Any hints?

**Comment by IanVS** [comment]
Can you copy in the full stack trace you get with `sane up`? Are you getting the same error with a new project?

**Comment by anasyb** [comment]
(Un)fortunately I stopped getting it after a random number of docker reboots! But it had been making a come back in the past... so I assume it will.. and when it does I'll be sure to capture that..

**Comment by mgenev** [comment]
I had the same intermittent weird failures with docker on osx :-/

**Comment by anasyb** [comment]
Hah... good one... though I was on Ubuntu deploying to the server, so its not Mac's fault ;-)
But yeah... I think its Compose to blame, not sane.
