### ISSUE TITLE
error in generate new project in linux fedora 21

### ISSUE THREAD

**Issue by albertosouza** [artificialio/sane#43]
I instaled sails, sane-cli and ember-cli and in the next step to create my app it shows this error:

```sh
sane new greatproject
ENOENT, no such file or directory '/usr/bin/lib/node_modules/sane-cli/package.json'
```

**Comment by Globegitter** [comment]
Hmmm, can you try `npm i -g https://github.com/artificialio/sane/tree/no-package-json-reference` and see if the issue is gone?

**Comment by albertosouza** [comment]
@Globegitter npm i -g https://github.com/artificialio/sane/tree/no-package-json-reference dont work

I fixed it in https://github.com/artificialio/sane/pull/50 for my system but need more tests in others systems.

**Comment by Globegitter** [comment]
Oh yeah the command would be `npm i -g git+https://github.com/artificialio/sane/tree/no-package-json-reference` (see the git+), but thank you for the PR

**Comment by albertosouza** [comment]
:)
