### ISSUE TITLE
sails-generate-auth

### ISSUE THREAD

**Issue by wayne-o** [artificialio/sane#46]
Hi

Is this supported? I couldn't run the sails generate auth command inside /api so had to run it at the level above but that doesn't look right? Are there any examples using this?

**Comment by Globegitter** [comment]
I think some of the people on the gitter channel have tried it out, but check out our official tutorials: https://github.com/mgenev/how-to-sane that are based on https://github.com/ryanwebber/sails-authorization

**Comment by mgenev** [comment]
So far the auth in 'how-to-sane' works well for me, I'm making improvements and adding session. It basically pends approval by @Globegitter and we can make into an official generator for sane.

**Comment by wayne-o** [comment]
How would you do social logins with this setup?

The code looks quite different to some of the examples I have seen - the
setup for instance is totally different.

On Tue, Jan 6, 2015 at 7:24 PM, Martin Genev <notifications@github.com>
wrote:

> So far the auth in 'how-to-sane' works well for me, I'm making
> improvements and adding session. It basically pends approval by
> @Globegitter <https://github.com/Globegitter> and we can make into an
> official generator for sane.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/artificialio/sane/issues/46#issuecomment-68918021>.
>



-- 
*--------------------*

*w://*

*t: 07508 215 459*

*--------------------*

**Comment by mgenev** [comment]
auth is in alpha and now lives here:
https://github.com/sane/sane-auth
