### ISSUE TITLE
Lean up Sails

### ISSUE THREAD

**Issue by Globegitter** [artificialio/sane#52]
The ember app takes kare of all the asset-pipeline etc and is either serverd through CDN or through the assets folder in sails. So remove everything frontend related completely.

 - [x] add views: false hook to .sailsrc (see below)
 - [x] remove views folder
 - [x] remove tasks folder
 - [x] remove Gruntfile.js
 - [x] `npm rm grunt ejs grunt-contrib-clean grunt-contrib-concat grunt-contrib-copy grunt-contrib-cssmin grunt-contrib-jst grunt-contrib-less grunt-contrib-uglify grunt-contrib-watch grunt-sails-linker grunt-sync --save`

This is what needs to be added to the `.sailsrc`:
```
{
  "hooks": {
    "views": false
  }
}
```

**Comment by remzr7** [comment]
What if you want to make a hybrid app client-server app? I feel this should be optional
