### ISSUE TITLE
Error on resource generation

### ISSUE THREAD

**Issue by GerDner** [artificialio/sane#53]
Then is try to generate a model like this in a new project:
```
sane generate resource user firstname:string lastname:string phone:string handy:string mail:string 
```
I get the following error.

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

ember-cli@0.1.7
npm@2.1.18
node@0.10.35
sane@0.0.17

MacOSX 10.10

Npm and node installed via homebrew.

Any idea? Perhaps any idea how i can get more infos about what happens there?

**Comment by Globegitter** [comment]
Thank you for the detailed version information. It seems like it can't access a certain binary, I will look into it asap and possibly add a flag for more debug information.
To make things a bit easier, are you running sane with docker?
If not do you have sails installed globally? Which version?

**Comment by GerDner** [comment]
I found the solution. I triggered the command from the folder /userfolder/project/ but i have to use it in /userfolder/project/projectname

Then the files are generated in /userfolder/project/projectname/client - /userfolder/project/projectname/server

**Comment by Globegitter** [comment]
Oh yeah you are right - I will make sure to add that to the documentation, that you always have to be in your root folder but also improve the error messages for that.
