### ISSUE TITLE
new projet impossible with debian

### ISSUE THREAD

**Issue by rkcreation** [artificialio/sane#57]
Hi,

When I try to create a new project :
*sane new testProject --docker --verbose*

it tells me :
*sane requires the latest docker/boot2docker/fig to be installed. Check https://github.com/artificialio/sane/blob/master/README.md for more details.
Exitting now.*

I have fig 1.01, Docker version 1.4.1, build 5bc2ff8, node v0.10.35, on Debian 7.1

It seems I fix this error in the file *lib/tasks/checkEnvironment.js line 19* by replacing

    if (self.boot2dockerExists() &&
      ['win32', 'darwin'].indexOf(process.platform) > -1) {
        return true;
    } else {
      return false;
    }

with

    if (['win32', 'darwin'].indexOf(process.platform) > -1) {
      if(self.boot2dockerExists()) {
        return true;
      } else {
        return false;
      }
    }

Thanks

**Comment by Globegitter** [comment]
@rkcreation can you also just check if
```js
    if (['win32', 'darwin'].indexOf(process.platform) > -1 &&
        self.boot2dockerExists() ) {
        return true;
    } else {
      return false;
    }
    return true;
  }
```
fixes it as well? 
I just turned around the check in the if, which should already skip boot2dockerExists() if it is on ubuntu.

**Comment by Globegitter** [comment]
I also pushed that to master so you can just install from there if you like.

**Comment by rkcreation** [comment]
@Globegitter it doesn't work either, if we are not on Windows or Mac, we shouldn't return false for boot2docker.

I think the algorithm is : 
 - check if it's on Windows or Mac (where boot2docker is necessary)
    - il self.boot2DockerExists() return true : all is ok
    - else : sane doesn't work, boot2docker missing
 - if it's not on Windows or Mac, we don't need boot2docker so it's ok

Code should be :
```javascript
  dockerExists: function() {
    if (!which('fig') || !which('docker')) {
      return false;
    }
    //check for windows or Mac OSX
    if (['win32', 'darwin'].indexOf(process.platform) > -1) {
      return self.boot2dockerExists();
    }
    return true;
  }
```

**Comment by Globegitter** [comment]
Oh yeah you are right, I wasn't thinking properly - thank you.
