### ISSUE TITLE
error when installing with npm install -g sane-cli ember-cli sails

### ISSUE THREAD

**Issue by alexjp** [artificialio/sane#59]
Hi,

I have been using sane in projects, today trying creating a new project, i stumbled with this error: 
Cannot find module '/home/alexandre/.npm-packages/lib/node_modules/sane-cli/node_modules/ember-cli/package.json'

The issue seems to be, if packages installed through npm install -g sane-cli ember-cli sails ,that problem happens.
If i then, in the folder i would create the new project, do a npm install sane-cli, it works afterwards.

Is this an issue or normal ?
Thanks!

**Comment by Globegitter** [comment]
hmmm that is strange I did change it in such a way that you do not need ember-cli as a global dependency anymore, but and should not happen.

What OS are you on?
And what are the commands you try to run? So after `npm install -g sane-cli` you try to run `sane new projectname` and that throws this error? Does e.g. `sane help` work?

**Comment by alexjp** [comment]
Sorry for taking time to answer, 

I tried it on Linux os, openSUSE to be exact.
The other questions, I think sane help was working, but please let me verify later on when i get home and to that particular machine.

**Comment by robe01** [comment]
I'm getting the same problem. I ran 'npm install -g sails ember-cli sane-cli' and the required npm files were installed successfully. Then I proceeded to running 'sane new project -d mongo' and then I get the following error below... 

Cannot find module 'c:\Users\Robert\AppData\Roaming\npm\node_modules\sane-cli\node_modules\ember-cli\package.json' 

I'm running this on windows 8.1.

**Comment by alexjp** [comment]
Tried again, and sane new project, and that error happens.

sane help outputs the normal help text.
sane version is 0.0.22

**Comment by Globegitter** [comment]
@alexjp @robe01 Thanks for getting back to me with those errors. I will test myself today or tomorrow.

**Comment by Globegitter** [comment]
@robe01 that is odd, I just installed again on my Windows 8.1 machine and it works fine. Can you maybe join the gitter channel https://gitter.im/artificialio/sane and we can debug more.

**Comment by catataw** [comment]
$ sane up

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

windows 8.1 version 0.22

**Comment by Globegitter** [comment]
@catataw Thanks for posting - that is a known error and Windows support needs to be fixed. See the end of this blog post: http://sanestack.com/blog/new-release-and-meeting-minutes/

**Comment by catataw** [comment]
@Globegitter Thank you, and congratulations for the great work

**Comment by Morganjackson** [comment]
I was seeing the same error as @catataw but on OS X using 0.0.23. I updated node to v0.12.0 and now I get the following:

→ sane up
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn ember ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)

**Comment by kriswill** [comment]
node 0.12 just came out, and I think some of the built-in module interfaces have changed.  So, it's entirely possible there is some compatibility problem in some node module dependency.

**Comment by Globegitter** [comment]
@Morganjackson That is odd, it is working on `iojs 1.1.0` for me. Just quickly switched to node 0.12 and tried `sane up --skip-ember`. I had to reinstall the npm packages but apart from that it seems fine.

**Comment by Morganjackson** [comment]
@Globegitter I ended up removing all packages and installed node v0.10.35 which got me back the the origianl error as seen below:

Thanks! 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by Morganjackson** [comment]
I also just noticed that running → ``sane generate resource user name:string age:number`` didnt generate the ember models.

info: Created a new controller ("user") at api/controllers/UserController.js!
info: Created a new model ("User") at api/models/User.js!

**Comment by Globegitter** [comment]
@Morganjackson just invited you to Gitter, maybe we can do a live debugging session at some point via screenhero.

**Comment by Morganjackson** [comment]
@Globegitter finally got it working! I uninstalled everything and then ``npm install -g sails sane-cli ember-cli`` which did the trick. 

However now I'm seeing the error below when opening http://localhost:1337/api/v1/users which crashes the whole app. 

Have you seen this before?

server   | /Users/morganjackson/Desktop/EmberSails/server/api/responses/ok.js:44
server   |   else return res.guessView({ data: data }, function couldNotGuessView () {
server   |                   ^
server   | TypeError: Object #<ServerResponse> has no method 'guessView'
server   |     at Object.sendOK (/Users/morganjackson/Desktop/EmberSails/server/api/responses/ok.js:44:19)
server   |     at ServerResponse.bound [as ok] (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
server   |     at found (/Users/morganjackson/Desktop/EmberSails/server/api/blueprints/find.js:76:9)
server   |     at bound (/usr/local/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:957:21)
server   |     at applyInOriginalCtx (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:416:80)
server   |     at wrappedCallback (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:315:18)
server   |     at _normalizeCallback.callback.success (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
server   |     at _switch (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
server   |     at returnResults (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:356:9)
server   |     at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:251:16
server   |     at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:82:7
server   |     at Object.async.each (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:121:20)
server   |     at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:425:11
server   |     at /usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:564:5
server   |     at Object.async.each (/usr/local/lib/node_modules/sails/node_modules/waterline/node_modules/async/lib/async.js:121:20)
server   |     at _buildChildOpts (/usr/local/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:453:9)

**Comment by Globegitter** [comment]
@Morganjackson Glad you could fix it. That is a very odd error, will look into it a bit now.

**Comment by Morganjackson** [comment]
@Globegitter Your a legend, worked perfectly!

**Comment by Globegitter** [comment]
Ahh, no idea why this even comes up but you might actually have just found some minor cleanup potential.

**Comment by albertosouza** [comment]
I think I could keep the views support the sails and just set the res.whantsJson based on a parameter of type url responseType

and print static html inside <noscript> tags

See no javascript version of: https://novo.atencaobasica.org.br/relato/4296

sails has suport for this feature by default and help with SEO ...

**Comment by Globegitter** [comment]
@albertosouza I think I want to keep views turned off as a default, since you have other services such as https://prerender.io/ and also https://github.com/tildeio/ember-cli-fastboot seems to be coming to us quite fast. 

But I should probably add a description to the docs how to turn it back on.

**Comment by mariusmateoc** [comment]
Hi,

I have the same problem on os x Yosemite. I run `npm install -g sails sane-cli ember-cli` then when I run `sane new project` I get this error:

`Cannot find module '/usr/local/lib/node_modules/sane-cli/node_modules/ember-cli/package.json'`

I use `node 0.12.0` and for npm globals I have: 

```
├── bower@1.3.12
├── ember-cli@0.1.15
├── grunt-cli@0.1.13
├── jshint@2.6.0
├── npm@2.5.1
├── sails@0.11.0
└── sane-cli@0.0.23
```

I reinstall node and all the packages but I get the same error.

**Comment by Globegitter** [comment]
@mariusmateoc That is very strange. Have not seen this yet at all. But yeah can you try to `npm rm -g ember-cli`.
Seems that `npm` has some issues with installing these 3 packages globally at once.

**Comment by mariusmateoc** [comment]
@Globegitter Thanks, removed all 3 packages with `npm uninstall -g <package_name>`, then I install them separately as follows:

```bash
npm install -g sails
npm install -g ember-cli
npm install -g sane-cli
```

Now it work as it should. Have a nice day!

**Comment by Globegitter** [comment]
@mariusmateoc Glad you got it working. Do you think you could do a PR on the gh-pages branch to the troubleshooting section, in the docs.md file? Would be really helpful.

**Comment by Globegitter** [comment]
Thank you for adding that @mariusmateoc

**Comment by e-karma** [comment]
FYI I encountered the same error, tried the uninstall/install of all 3 separately first; didn't work.  Then removed lines 27 + 29 alluded to earlier, and it worked.  Thanks

**Comment by Globegitter** [comment]
@e-karma I am glad you got this working. Which lines exactly did you remove?

**Comment by albertosouza** [comment]
@Globegitter thanks for sharing these options to server side rendering, will be very useful.
I was using onw sails.js build-in feature to load and render a static version of the system but https://prerender.io/ seens to be a better option
