### ISSUE TITLE
camelcase root name of json entity on multi word models

### ISSUE THREAD

**Issue by alexjp** [artificialio/sane#61]
Hi,

i am having a problem, with a model that is called like : modelName. 
Currently in sane stack blueprints, the root name in json for that model is modelname, but ember expects modelName. is something badly configured in my end ?

strangelly, if that same model is in json as an association, it is as modelName.

One workaround i did was creating a model.emberName in models and then, on the function emberizeJSON of blueprints, use that:
```
emberizeJSON: function ( model, records, associations, sideload ) {
    sideload = sideload || false;

    var plural = Array.isArray( records ) ? true : false;
    var hasEmberName = typeof model.emberName !== 'undefined';
    var emberName = hasEmberName ? model.emberName : model.identity;

    var documentIdentifier = plural ? pluralize( emberName ) : emberName;
```

and then that specific model has emberName: "modelName",

**Comment by Globegitter** [comment]
This sounds like a bug in https://github.com/mphasize/sails-generate-ember-blueprints, specifically in this file: https://github.com/mphasize/sails-generate-ember-blueprints/blob/694ea1594b50a26c5a5d68f9b2cfddec15cdaa26/templates/api/blueprints/_util/actionUtil.js

If you have time a PR for that library would be greatly appreciated.

**Comment by alexjp** [comment]
Yeah, that was also the file i changed when i added the code in the previous message.
I currently dunno how to "properly" fix it, since sails.js seems to do a model.identity.toLowerCase() :
``` 
module.identity = module.identity.toLowerCase();
```
in file node_modules/sails-build-dictionary/index.js, line 120.

**Comment by Globegitter** [comment]
https://github.com/mphasize/sails-generate-ember-blueprints/pull/6 should fix the error. If someone could test, simply by manually changing the lines to:
```js
    var documentIdentifier = plural ? pluralize( model.globalId ) : model.globalId;
    //turn id into camelCase for ember
    documentIdentifier = documentIdentifier.replace(/(?:^\w|[A-Z]|\b\w|\s+)/g,
    function(match, index) {
      if (+match === 0) return ""; // or if (/\s+/.test(match)) for white spaces
      return index == 0 ? match.toLowerCase() : match.toUpperCase();
    });
```
that would be great.

**Comment by kylenathan** [comment]
Can confirm this does the job. Thanks @Globegitter

**Comment by Globegitter** [comment]
Awesome @kylenathan https://github.com/mphasize/sails-generate-ember-blueprints/releases/tag/v0.0.3 has been released and every newly generated project should use that automatically.

**Comment by alexjp** [comment]
@Globegitter  thanks for the fix !
worked here too!
