### ISSUE TITLE
On sane new: EACCES, permission denied 'server/.sailsrc'

### ISSUE THREAD

**Issue by IanVS** [artificialio/sane#70]
I'm new to sane, so maybe I'm doing something wrong, but when I try to run `sane new project --docker` I receive the following:

      create tests/.jshintrc
      create tests/helpers/resolver.js
      create tests/helpers/start-app.js
      create tests/index.html
      create tests/test-helper.js
      create tests/unit/.gitkeep
      create vendor/.gitkeep
    Installed packages for tooling via npm.
    Installed browser packages via Bower.
    Running tooling scrips for Sane....EACCES, permission denied 'server/.sailsrc'
    Running tooling scrips for Sane...

and the foldersize sits at 190M, so I'm guessing it's hung up.  The entire `server/` folder is owned by root, whereas it is owned by my user when I `sane new project` without docker.

I am using:

    sane: 0.0.23
    fig: 1.0.1
    docker: 1.5.0, build a8a31ef

and I have DOCKER_HOST set as suggested in https://gist.github.com/RuslanHamidullin/94d95328a7360d843e52

**Comment by Globegitter** [comment]
@IanVS I ran into the exact same issues when testing on my Ubuntu machine, please also raise your voice here as well: https://github.com/docker/fig/issues/744

The problem is related to what you mention in https://github.com/artificialio/sane/issues/69 that you did install as root. I suppose I could add some solution that asks for the password so it does not hang, but not sure if that is the best solution.

**Comment by Globegitter** [comment]
https://github.com/docker/fig/issues/744#issuecomment-74054132 are the steps I did to fix this issue if I remember correctly (has been some time).

**Comment by IanVS** [comment]
I tried these steps separately last night (adding myself to docker group, then removing that group and changing /etc/default/docker).  I'll try combining to see if this helps, but I think that either of those methods has the effect of allowing Docker to run outside of sudo, which according to their docs is not recommended.

It seems like this particular issue is related to the USER that docker is running as.  I'll make a comment in the issue you mention, because this seems like a docker/fig question.

**Comment by IanVS** [comment]
Alright, well I was able to hack together a quick solution.  The problem is that by default the fig user is root, which is why the `server/` folder is created with `root:root` ownership, causing the EACCES error reported in this issue.  This happens regardless if the steps mentioned in docker/fig#744 (comment) are followed.  Those steps only give non-root access, but do not change the fact that fig runs (and creates files) as root.

Adding the non-root user id to the fig.yaml file will cause the `server/` folder to be created with that user's ownership.  Great!  But then `npm install` fails because it needs to be root.  Doh!  So, my kludge was to initially prepare the fig.yaml with the user id, and then after `sails up` is executed, overwrite it with a version that does not include `user`.  

It's too late now, but I'll try to clean things up and submit a PR, if only to better explain what I did and get feedback of whether there's a better way to accomplish it.

**Comment by IanVS** [comment]
I believe the "right" solution to this issue is to be able to run `fig run server sails new .` as the non-root user which launched `sane new`.  There is a request at the fig project to do just that, https://github.com/docker/fig/issues/939.  Until that happens, the only way I know of to fix this is to modify the fig.yaml file before and after running the `fig run server sails new .`  That was how I solved it in my previous comment.  I'll get working on that PR. I've never made one before, so please have mercy! :fearful:

**Comment by johnhitz** [comment]
@ianVS @Globegitter I'm confused...In the quickstart it says 'sane new project --docker creates project with sails-disk and Docker'. If I run fig run server sails new . as you suggest I get 'Can't find fig.yml. Are you in the right directory?' Why aren't we using a Dockerfile? What am I missing?

**Comment by IanVS** [comment]
@johnhitz fig run server sails new . is run inside the sane new script, which also copies over a fig.yml file that is needed.  I was discussing ways in which sane could be modified, not commands the end user would run. That make any sense?

**Comment by johnhitz** [comment]
@IanVS Ok! That's what I though. But I can't get past the point of 'sane new testProject --docker' not being able to connect to Docker daemon at http://localhost:4243. I followed Markus's instruction and still can't get it to work. I'm guess I am some what confused as to why the 'sane new project --docker' command does not pull a docker container from docker hub  with a Dockerfile which initiates this whole structure...isn't that the point of Docker?

**Comment by IanVS** [comment]
@johnhitz I'm no expert on any of this, but from what I can tell, fig is what does the pulling of the dockerfile.  You'll notice in the fig.yml file (or the template, if you can't get it to the point where it builds the actual file), there is a `image: artificial/docker-sails:stable-pm2` This is a reference to the docker container and dockerfile at https://registry.hub.docker.com/u/artificial/docker-sails/. Fig just seems to be an abstraction layer on top of docker which does the pulling containers like you expected.

Have you checked to make sure the Docker daemon is running on your box?  Have you tried restarting?  It sounds like you're stuck on issue #69?

**Comment by johnhitz** [comment]
Docker is running. I have restarted. My DOCKER_HOST is set...I have not added myself as a user because from what I understand this is a security issue. And, I would prefer not to open up a known security whole when there seem to be plenty which are unknown.

**Comment by IanVS** [comment]
The way it was explained to me, it's only a security issue if you open up the Docker container to the outside world, e.g. for Android or IOS testing.  I'd say if it's a concern for you, it's still possible to get a lot out of the sane stack without running Docker.  And maybe at some point we can figure out how to avoid the root/non-root issue for Linux altogether.

**Comment by johnhitz** [comment]
Ok! I am just trying to learn anyway. So I guess I will just play and see where it takes me! Thanks for your help!

**Comment by pranksinatra** [comment]
This is by no means an elegant solution, but in Ubuntu right after starting a sane installation:
`sane up my-sane-project --docker`
I'll jump into another terminal and do
`sudo chown -R micah my-sane-project/server/`
which resolves this file permissions bug.

**Comment by kriswill** [comment]
Another thing to consider is delegating permissions to your user on linux.  see: http://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo

**Comment by Globegitter** [comment]
It is also mentioned here https://docs.docker.com/installation/ubuntulinux/#giving-non-root-access as well as now also here: http://sanestack.com/#sane-stack-troubleshooting-giving-docker-non-root-access

That is imo the preferred solution, even though it should now be fixed from within sane.

**Comment by IanVS** [comment]
The problem is that even with giving non root access as specified in those links, docker-compose will still by default create the /server folder with root ownership, causing subsequent steps inside sane cli to fail.

**Comment by Globegitter** [comment]
Hmmm, I wonder what I did on my Linux to not run into this issue :P
But yeah thanks for the workaround - that should bring everyone in a good position now.

**Comment by kriswill** [comment]
@IanVS that should only happen if 1 you run `sane` as sudo, and 2 your node is installed with node_modules owned by root.

**Comment by IanVS** [comment]
Unless specified otherwise in the Docker-compose.yml, I found that the default user for the actions undertaken by docker-compose is root, no matter how sane is run and no matter how node is installed. I have node installed without sudo, and definitely didn't sudo sane, and the server directory was still owned by root.

**Comment by vabatta** [comment]
As reported here, there isn't a solution yet right? I exactly get the error posted on top of this issue, but none of the tricks above works.
I can run ```docker run hello-world``` without ```sudo``` as well as ```npm install -g <package>``` (on my local arch linux). Some news about a fix? Or another hacks (also dirty) just to start working?

**Comment by IanVS** [comment]
This should already be fixed. What version of SANE are you using?

**Comment by vabatta** [comment]
Latest, I downloaded it tonight

**Comment by IanVS** [comment]
What is the output you are seeing?

You can also try using `npm i -g sane-cli@0.1.0-beta.2`, but I don't think that will change anything for you, the fix for this issue came earlier than that.

**Comment by vabatta** [comment]
The output is exactly the same of the post at top

**Comment by IanVS** [comment]
Can you hop in the gitter room?  Let's try to troubleshoot it there.

**Comment by IanVS** [comment]
The issue turned out to be: https://github.com/artificialio/sane/issues/176
