### ISSUE TITLE
Wrong dependency message points to ember-cli

### ISSUE THREAD

**Issue by vire** [artificialio/sane#72]
running `sane new testProject -d disk`

results into:

```
sane requires the latest sails to be installed. Run npm install -g ember-cli.
Exitting now.
```

```
$ sane -V
0.0.23
```

and 

```
ember --version
version: 0.1.15
node: 0.11.14
npm: 2.1.8
```

**Comment by vire** [comment]
running `sane new testProject -d disk --docker` works, but there is the #70 issue

**Comment by Globegitter** [comment]
Ahh thank you for that https://github.com/artificialio/sane/commit/3894aa96f906629f123706bc0e71b3b911051a7a fixes that.

So do try to run `npm i -g sails` and run `sane new` again.
