### ISSUE TITLE
Is it normal to have to sudo every command for sane to work?

### ISSUE THREAD

**Issue by Jordan4jc** [artificialio/sane#74]
I have to run everything with sudo, is this normal or is there a way to get around it, I installed rbenv because I thought that would get around it. I'm still a little unfamiliar with this kind of thing but I feel like I've used sane in the past without having to do all that.

**Comment by kriswill** [comment]
It depends on how you installed your node | io.js, and docker if you use it.  On OS/X (which I use), there is a general best practice that a user should never install software as root, unless it has to implement some system-level driver.  Homebrew, which is the most prevalent software package system for OS/X does not allow you to install anything using sudo, so when using it, nothing it installs will need it.  This includes tools such as `nvm`, `docker`, `boot2docker`, `virtualbox`, and so on.

**Comment by Jordan4jc** [comment]
I've never heard of nvm, if I uninstalled node and my node packages and used homebrew to install node via NVM instead of the installer I would theoretically be able to get around the need for using sudo for everything?

**Comment by kriswill** [comment]
If you used nvm to install node, you would not need to use sudo for node.

**Comment by vire** [comment]
@Jordan4jc 
whats the output when u type:

```
ls -la `which node`
```
and



```
ls -la `which npm`
```

generally npm and node commands must not prompt you to use sudo, but there is a small issue with fig where everything generated is owned by root.

**Comment by kriswill** [comment]
```sh
→ ls -la `which node` && ls -la `which npm`
-rwxr-xr-x  1 kris  staff  18581248 Feb  6 12:42 /Users/kris/.nvm/versions/node/v0.12.0/bin/node
lrwxr-xr-x  1 kris  staff  38 Feb  6 12:42 /Users/kris/.nvm/versions/node/v0.12.0/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js

→ nvm use iojs
Now using io.js v1.2.0

→ ls -la `which node` && ls -la `which npm`
lrwxr-xr-x  1 kris  staff  4 Feb 10 19:01 /Users/kris/.nvm/versions/io.js/v1.2.0/bin/node -> iojs
lrwxr-xr-x  1 kris  staff  38 Feb 10 19:01 /Users/kris/.nvm/versions/io.js/v1.2.0/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
```

if you're using fig, then this wouldn't apply to sails, because sails will be running in a docker container, which has it's own node.

**Comment by kriswill** [comment]
my `server` app in sane is actually called `api`, and you can run something like this to get information about node:
```sh
→ fig run api node -p process.versions
{ http_parser: '2.3',
  node: '0.12.0',
  v8: '3.28.73',
  uv: '1.0.2',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1l' }

→ fig run api npm --version
2.5.0
```

**Comment by Jordan4jc** [comment]
```ls -la `which node`
lrwxr-xr-x  1 jordanriser  admin  30 Feb 14 22:49 /usr/local/bin/node -> ../Cellar/node/0.12.0/bin/node```

```ls -la `which npm`
lrwxr-xr-x  1 jordanriser  admin  46 Feb 14 22:49 /usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js```

So should I remove node and npm + packages from my system and install node via nvm instead? Is that going to be the better option? I was not running sane new with the `--docker` flag so I wasn't using docker, I'm not really sure what it is so for the purpose of just testing and learning I am just using it without docker

**Comment by vire** [comment]
NVM is the best solution I've recommend, you can be 100%sure it installs all filed into /home/$USER/.nvm/... directory which is owned by you and you don't need to enter sudo password.

It's a indicator of incorrect installed node/npm (with sudo perhaps) when you need to enter root passwd on normal operations like `sane up` or `sane generate resource user name:string age:number`.

The benefit of NVM is comfort of not carrying about everything else, just writing node code :)

**Comment by Jordan4jc** [comment]
I'm in the process of uninstalling node so I can install with nvm

I'm using this link here

http://hungred.com/how-to/completely-removing-nodejs-npm/

and when I go into 

`/usr/local/share/man/man1/` I see node.1 and also a bunch of npm-*.1 files should I remove those as well even if this guide doesn't say anything about those?

**Comment by vire** [comment]
@Jordan4jc the path you've posted si for manpages, so you can purge everything related to node from there with no worry, I think nvm installs them for you again, so you can run `$ man node`

**Comment by Jordan4jc** [comment]
Can I also remove all npm and node files from the other man folders? I have 4 and each one has some amount of node or npm related files.

Sorry I'm asking so many questions, I don't really know anyone who is an expert in this area and I don't want to really screw up my computer.

**Comment by vire** [comment]
Generally, removing manpages does not affect functionality :), You can add them back whenever you need, but If you want, you can just ignore them, the want cause no harm.

**Comment by mgenev** [comment]
closing this, nvm works very well for this
