### ISSUE TITLE
guessView fallback not working

### ISSUE THREAD

**Issue by vire** [artificialio/sane#75]
Hi, I've tried out today sane without docker (just `sane new testProjectSane)

and running `sane generate new resource user name:string age:number` generated the resource, but trying to view it as raw by visiting `localhost:1337/api/v1/users` crashes the server

```javascript
$ testProjectSane/server/api/responses/ok.js:44
else return res.guessView({ data: data }, function couldNotGuessView () {
                        ^
TypeError: undefined is not a function
```

**Comment by IanVS** [comment]
I believe your problem is in the syntax of your command.  Instead, try running `sane generate resource user name:string age:number` (without the "new").

**Comment by vire** [comment]
@IanVS sry I made an typo by rewriting, the **new** shouldn't be there,

i type just `sane generate resource user name:string age:number`

it outputs:
```
$ sane generate resource user name:string age:number
version: 0.1.15
info: Created a new controller ("user") at api/controllers/UserController.js!
info: Created a new model ("User") at api/models/User.js!
installing
  create app/models/user.js
installing
  create tests/unit/models/user-test.js
installing
  create app/routes/user.js
  create app/templates/user.hbs
installing
  create tests/unit/routes/user-test.js
```

accesing the URL `http://127.0.0.1:1337/api/v1/users` in browser results to:

```
server   | /workspace/testProject/server/api/responses/ok.js:44
server   |   else return res.guessView({ data: data }, function couldNotGuessView () {
server   |          
server   |          ^
server   | TypeError: Object #<ServerResponse> has no method 'guessView'
server   |     at Object.sendOK (/home/vire/workspace/testProject/server/api/responses/ok.js:44:19)

```

but `$ curl http://127.0.0.1:1337/api/v1/users` gives:

```
{
  "users": []
}```

**Comment by vire** [comment]
[duplicate] #65
