### ISSUE TITLE
Autoreload server on file change

### ISSUE THREAD

**Issue by Systho** [artificialio/sane#77]
Hello, 

it's quite annoying to have to restart sane every time we change a server file. 
Would it be possible to use the watcher already present for the client with the server files ?

There is a sails hook here providing this feature  but it does not seem to work with sane : https://github.com/sgress454/sails-hook-autoreload

I'm really new to Javascript on server and Node.js so I do not feel confident enough to work on a PR or even evaluate the amount of work it would require but I would love not going to my console to restart sane every time my server changes

**Comment by Globegitter** [comment]
@Systho You are right there seems to be an issue related to docker. If you use it without it should work fine though. I did just add that `sane up` is automatically appending the `--verbose flag` for sails so from the next version on you should see that the reload works.

Will look into docker support. But once that is fixed, was planning to add that. A PR once that is done would be accepted as well. It is quite simple, just adding it to https://github.com/artificialio/sane/blob/master/lib/commands/new.js#L290 :)

**Comment by Globegitter** [comment]
@Systho Latest version `0.11.4` of the autoreload hook fixes docker support, but it needs a custom setting for it. So you would also have to add a `_autoreload.js` to https://github.com/artificialio/sane/tree/master/templates/server/config that pre-configures the autoreload settings based on the `--docker` flag.

I know it can be daunting to get started with adding a new feature to a relatively big project, but I would encourage you to give it a try. If you have any more questions to get started I would be more than happy to answer them :)

**Comment by Globegitter** [comment]
Just tested and working with `config/autorelaoad.js`
```
var path = require('path');

module.exports.autoreload = {
  active: true,
  //use polling to watch file changes
  //slower but needed for the docker image
  usePolling: true, // this would be a variable in the template, probably {{autoPolling}}
  // Set dirs to watch
  dirs: [
    path.resolve('api','controllers'),
    path.resolve('api','models')
  ]
};
```

@Systho Feel up for the challenge?

**Comment by Systho** [comment]
I've done my best following your advices. It doesn't completely work as I would (editing blueprints for instance requires a full restart ) but that's mainly a concern for sails-hook-autoreload project.

Thank you for help (and I mean doing all the work ;) )
