### ISSUE TITLE
How to use WebSockets between Ember and Sails ?

### ISSUE THREAD

**Issue by Systho** [artificialio/sane#83]
Would you have any pointer guiding to an example of using a socket between an Ember Controller and a Sails Controller ?

**Comment by Globegitter** [comment]
Yep that is something quite untouched by sane so far - has not been in my critical path yet. But I know off these three projects:
- https://github.com/Wildhoney/EmberSockets
- https://github.com/huafu/ember-data-sails
- https://github.com/bmac/ember-data-sails-adapter

Hope that helps a bit and maybe someone else from the community can pitch in.

**Comment by Systho** [comment]
Thank you, 

I've managed to have EmberSockets installed but during the initialization it complains about `[Report Only] Refused to connect to 'ws://localhost:4200/socket.io/?EIO=3&transport=websocket&sid=nEtyYpIlTX9mFJg5AAAC' because it violates the following Content Security Policy directive: "connect-src 'self' ws://localhost:35729 ws://0.0.0.0:35729".`

35729 seems to be the port on wich livereload is working : `client   | Livereload server on port 35729`

In sails there is a wrapper for socket.io but I'm not sure what it does, or it works or even how to use it in ember. the wrapper can be found at `server/assets/js/dependencies/sails.io.js`

This is everything I've managed to find so far but I'm lost on how to connect the dots. If someone has more info on the topic I'd be glad to hear from them

**Comment by Systho** [comment]
I managed to get rid of the security report by dropping the ember-cli-content-security-policy package. It's probably not a good idea but at least I'm progressing.

I also managed to get the `sails.io.js` in my browser by copying the file in my `client/vendor` directory and adding the following line in my Brocfile `app.import('vendor/sails.io.js');`

**Comment by kriswill** [comment]
I wouldn't drop content-security-policy, because you can use it's values to populate the headers when you go live.  Also, `ws://localhost:4200` doesn't look right for sails, shouldn't it be a different port?  Anyways, you can just add it to the list of accepted `connect-src` in your `config/environment.js`

**Comment by Systho** [comment]
I'll bring back content-security-policy security then and try to customize it. localhost:4200 is the host and the port on which I go on my browser so I was expecting it is the address I should use but if I understand it correctly when I go live , my ember app will be served by sails so I should use the sails address and port in dev (1337) , then ?

**Comment by kriswill** [comment]
You can host the ember app with the sails app, and I think that's what @Globegitter and @mgenev do with theirs.  I host separately using ember-deploy, with assets going to an S3 bucket and the HTML riding in a Redis database and served up from node.js, where I can version select the SHA1 for the ember app, and set a SHA1 as the default.  This helps me to stage the app, prior to going live with it.

**Comment by kriswill** [comment]
@Systho also, sails.js uses the same port as HTTP, which is 1337 in development.

**Comment by Kulja** [comment]
@Systho I am also trying to use sockets between ember and sails. I am using at the moment https://github.com/huafu/ember-data-sails with sails 0.11 which is not working at the moment but update should be out soon. Look here https://github.com/huafu/ember-data-sails/issues/2

**Comment by Systho** [comment]
Thank you for your help Kulja. I think I have found the cause of your issue and proposed a workaround (but no real clean fix because my JS skills are too low  ;) ) . 

I'm looking forward to use ember-data-sails

**Comment by Kulja** [comment]
I am glad I could help out. I saw your proposed solution, good job!

**Comment by Globegitter** [comment]
@Systho @Kulja we now have official websocket support: http://sanestack.com/#sane-stack-sails-ember-websockets

I haven't had the chance to test it myself, so report any bugs if that doesn't work. Closing this in the meantime.

**Comment by Systho** [comment]
Awesome, I'm trying it immediately !
Many thanks to all of you

**Comment by huafu** [comment]
yeah fix http://sanestack.com/#sane-stack-sails-ember-websockets and remove `In the meantime just add app.import('vendor/js/sails.io.js'); to your Brocfile.js`, I forgot to update readme, this is not needed anymore.

**Comment by Globegitter** [comment]
@huafu thanks and done.

**Comment by huafu** [comment]
oh my comment was kinda said in a rude way, result of answering at 4am with a huge hangover haha, anyway, thanks for the update ;-)
