### ISSUE TITLE
SANE resource library 

### ISSUE THREAD

**Issue by mgenev** [artificialio/sane#94]
We throw a whole lot of resources related to the stack around in the chat, I suggest that we figure out a way to make a public library out of them for future reference.

we can tag them by what component of the stack they are about or the stack itself - sane, ember, sails, docker etc.

**Comment by Globegitter** [comment]
Yep that is a very good idea @mgenev I'll have a think about it.

**Comment by mgenev** [comment]
Resource Library is now to be found here: https://github.com/sane/sane-auth
