### ISSUE TITLE
Sending badRequest when unauthorized should have been sent

### ISSUE THREAD

**Issue by anasyb** [artificialio/sane#98]
ember-simple-auth expects an unauthorized access (401) to be sent when an issue happens with the auth. At the moment sails is sending a badRequest (400).

*Why?*
- In response to receiving 401, simple-auth "invalidates the session and reloads the application" [ref](http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-ApplicationRouteMixin-authorizationFailed).

*Fix*
- update ```AuthController.js``` to call res.unauthorized instead of res.badRequest
- include an api/responses/unauthorized.js file

**Comment by Globegitter** [comment]
@anasyb Isn't that an issue with https://github.com/Globegitter/sane-auth?

**Comment by anasyb** [comment]
I guess so... will open it there. Sorry!
